name: community_tutorial
channels:
- conda-forge
- bioconda
- r
- defaults
- anaconda
dependencies:
- lxml
- notebook
- nb_conda_kernels
- r-essentials
- r-irkernel
- r-devtools
- r-ggplot2
- r-gridextra
- r-dendsort
- bioconductor-complexheatmap
- r-igraph
- r-circlize
- r-r.utils
- r-data.table
- r-ggrepel